;; SRFI 151: Bitwise operations
;;
;; Every example the SRFI gives, and the argument checking it leaves to the
;; implementation: each procedure refuses what is not an exact integer, and a
;; bit index, a field's bounds or a length that is negative.

(import (scheme base)
        (srfi 151))

(test-group "SRFI 151 - basic operations"
  (test "bitwise-not" -11 (bitwise-not 10))
  (test "bitwise-not of a negative" 36 (bitwise-not -37))
  (test "bitwise-and" 10 (bitwise-and 11 26))
  (test "bitwise-and of none is -1" -1 (bitwise-and))
  (test "bitwise-and of one is itself" 7 (bitwise-and 7))
  (test "bitwise-and of three" 2 (bitwise-and 14 11 7))
  (test "bitwise-ior" 11 (bitwise-ior 3 10))
  (test "bitwise-ior of none is 0" 0 (bitwise-ior))
  (test "bitwise-xor" 9 (bitwise-xor 3 10))
  (test "bitwise-xor of none is 0" 0 (bitwise-xor))
  (test "bitwise-eqv" -42 (bitwise-eqv 37 12))
  (test "bitwise-eqv of none is -1" -1 (bitwise-eqv))
  (test "bitwise-eqv of one is itself" 5 (bitwise-eqv 5))
  (test "bitwise-eqv of three is (bitwise-eqv a (bitwise-eqv b c))"
        (bitwise-eqv 37 (bitwise-eqv 12 99)) (bitwise-eqv 37 12 99))
  (test "bitwise-nand" -11 (bitwise-nand 11 26))
  (test "bitwise-nor" -28 (bitwise-nor 11 26))
  (test "bitwise-andc1" 16 (bitwise-andc1 11 26))
  (test "bitwise-andc2" 1 (bitwise-andc2 11 26))
  (test "bitwise-orc1" -2 (bitwise-orc1 11 26))
  (test "bitwise-orc2" -17 (bitwise-orc2 11 26))
  (test "on integers beyond 2^53" (+ (expt 2 100) 1) (bitwise-ior (expt 2 100) 1))
  (test "and negative ones beyond it" (- (expt 2 100)) (bitwise-and (- (expt 2 100)) -1)))

(test-group "SRFI 151 - integer operations"
  (test "arithmetic-shift left" 32 (arithmetic-shift 8 2))
  (test "arithmetic-shift right" 4 (arithmetic-shift 8 -1))
  (test "arithmetic-shift by nothing" 4 (arithmetic-shift 4 0))
  (test "arithmetic-shift right rounds towards negative infinity" -79
        (arithmetic-shift -100000000000000000000000000000000 -100))
  (test "bit-count of 0" 0 (bit-count 0))
  (test "bit-count of -1" 0 (bit-count -1))
  (test "bit-count of 7" 3 (bit-count 7))
  (test "bit-count of 13" 3 (bit-count 13))
  (test "bit-count of -13 counts its 0 bits" 2 (bit-count -13))
  (test "bit-count of 30" 4 (bit-count 30))
  (test "bit-count of -30" 4 (bit-count -30))
  (test "bit-count of 2^100" 1 (bit-count (expt 2 100)))
  (test "bit-count of -2^100" 100 (bit-count (- (expt 2 100))))
  (test "bit-count of -(2^100 + 1)" 1 (bit-count (- (+ 1 (expt 2 100)))))
  (test "integer-length of 0" 0 (integer-length 0))
  (test "integer-length of 1" 1 (integer-length 1))
  (test "integer-length of -1" 0 (integer-length -1))
  (test "integer-length of 7" 3 (integer-length 7))
  (test "integer-length of -7" 3 (integer-length -7))
  (test "integer-length of 8" 4 (integer-length 8))
  (test "integer-length of -8" 3 (integer-length -8))
  (test "bitwise-if" 9 (bitwise-if 3 1 8))
  (test "bitwise-if, the other way" 0 (bitwise-if 3 8 1))
  (test "bitwise-if, a single bit" 3 (bitwise-if 1 1 2))
  (test "bitwise-if, fields" #b00110011 (bitwise-if #b00111100 #b11110000 #b00001111)))

(test-group "SRFI 151 - single bits"
  (test "bit-set?, clear" #f (bit-set? 1 1))
  (test "bit-set?, set" #t (bit-set? 0 1))
  (test "bit-set? of 10" #t (bit-set? 3 10))
  (test "bit-set? far beyond a negative's length" #t (bit-set? 1000000 -1))
  (test "bit-set? of 6, bit 2" #t (bit-set? 2 6))
  (test "bit-set? of 6, bit 0" #f (bit-set? 0 6))
  (test "copy-bit sets bit 0" #b1 (copy-bit 0 0 #t))
  (test "copy-bit sets bit 2" #b100 (copy-bit 2 0 #t))
  (test "copy-bit clears a bit" #b1011 (copy-bit 2 #b1111 #f))
  (test "bit-swap" #b1 (bit-swap 0 2 4))
  (test "bit-swap of equal bits changes nothing" 6 (bit-swap 1 2 6))
  (test "any-bit-set?" #t (any-bit-set? 3 6))
  (test "any-bit-set?, none" #f (any-bit-set? 3 12))
  (test "every-bit-set?" #t (every-bit-set? 4 6))
  (test "every-bit-set?, not all" #f (every-bit-set? 7 6))
  (test "first-set-bit of 1" 0 (first-set-bit 1))
  (test "first-set-bit of 2" 1 (first-set-bit 2))
  (test "first-set-bit of 0 is -1" -1 (first-set-bit 0))
  (test "first-set-bit of 40" 3 (first-set-bit 40))
  (test "first-set-bit of -28" 2 (first-set-bit -28))
  (test "first-set-bit of 2^99" 99 (first-set-bit (expt 2 99)))
  (test "first-set-bit of -2^99" 99 (first-set-bit (expt -2 99))))

(test-group "SRFI 151 - bit fields"
  (test "bit-field from 0" #b1010 (bit-field #b1101101010 0 4))
  (test "bit-field from 3" #b101101 (bit-field #b1101101010 3 9))
  (test "bit-field from 4" #b10110 (bit-field #b1101101010 4 9))
  (test "bit-field to the top" #b110110 (bit-field #b1101101010 4 10))
  (test "bit-field of one bit" 0 (bit-field 6 0 1))
  (test "bit-field of two" 3 (bit-field 6 1 3))
  (test "bit-field beyond the length" 1 (bit-field 6 2 999))
  (test "bit-field beyond 2^128" 1 (bit-field #x100000000000000000000000000000000 128 129))
  (test "bit-field of an empty field" 0 (bit-field 6 2 2))
  (test "bit-field-any?" #t (bit-field-any? #b1001001 1 6))
  (test "bit-field-any?, none" #f (bit-field-any? #b1000001 1 6))
  (test "bit-field-every?" #t (bit-field-every? #b1011110 1 5))
  (test "bit-field-every?, not all" #f (bit-field-every? #b1011010 1 5))
  (test "bit-field-clear" #b100000 (bit-field-clear #b101010 1 4))
  (test "bit-field-set" #b101110 (bit-field-set #b101010 1 4))
  (test "bit-field-replace" #b100100 (bit-field-replace #b101010 #b010 1 4))
  (test "bit-field-replace, bit 0" #b111 (bit-field-replace #b110 1 0 1))
  (test "bit-field-replace, bit 1" #b110 (bit-field-replace #b110 1 1 2))
  (test "bit-field-replace uses only the source's low bits" #b100100 (bit-field-replace #b101010 #b11010 1 4))
  (test "bit-field-replace-same" #b1001 (bit-field-replace-same #b1111 #b0000 1 3))
  (test "bit-field-rotate by 0" #b110 (bit-field-rotate #b110 0 0 10))
  (test "bit-field-rotate by 0, a wide field" #b110 (bit-field-rotate #b110 0 0 256))
  (test "bit-field-rotate past the top bit" 1 (bit-field-rotate #x100000000000000000000000000000000 1 0 129))
  (test "bit-field-rotate of one bit" #b110 (bit-field-rotate #b110 1 1 2))
  (test "bit-field-rotate towards the high bits" #b1010 (bit-field-rotate #b110 1 2 4))
  (test "bit-field-rotate towards the low bits" #b1011 (bit-field-rotate #b0111 -1 1 4))
  (test "bit-field-rotate of an empty field" 6 (bit-field-rotate 6 3 2 2))
  (test "bit-field-reverse of two bits" 6 (bit-field-reverse 6 1 3))
  (test "bit-field-reverse of three" 12 (bit-field-reverse 6 1 4))
  (test "bit-field-reverse of 32 bits" #x80000000 (bit-field-reverse 1 0 32))
  (test "bit-field-reverse of 31" #x40000000 (bit-field-reverse 1 0 31))
  (test "bit-field-reverse of 30" #x20000000 (bit-field-reverse 1 0 30))
  (test "bit-field-reverse of 129" 5 (bit-field-reverse #x140000000000000000000000000000000 0 129)))

(test-group "SRFI 151 - bits as lists and vectors"
  (test "bits->list" '(#t #f #t #f #t #t #t) (bits->list #b1110101))
  (test "bits->list, longer than the integer" '(#t #t #f #f #f) (bits->list 3 5))
  (test "bits->list, with a length" '(#f #t #t #f) (bits->list 6 4))
  (test "bits->list, shorter than the integer" '(#f #t) (bits->list 6 2))
  (test "bits->list of 0" '() (bits->list 0))
  (test "bits->vector" #(#t #f #t #f #t #t #t) (bits->vector #b1110101))
  (test "bits->vector, with a length" #(#t #t #f #f #f) (bits->vector 3 5))
  (test "list->bits" #b1110101 (list->bits '(#t #f #t #f #t #t #t)))
  (test "list->bits, low zeros" #b111010100 (list->bits '(#f #f #t #f #t #f #t #t #t)))
  (test "list->bits of three" 6 (list->bits '(#f #t #t)))
  (test "list->bits, a high zero" 6 (list->bits '(#f #t #t #f)))
  (test "list->bits of four" 12 (list->bits '(#f #f #t #t)))
  (test "list->bits of none" 0 (list->bits '()))
  (test "vector->bits" #b1110101 (vector->bits #(#t #f #t #f #t #t #t)))
  (test "vector->bits, low zeros" #b111010100 (vector->bits #(#f #f #t #f #t #f #t #t #t)))
  (test "vector->bits of three" 6 (vector->bits #(#f #t #t)))
  (test "vector->bits, a high zero" 6 (vector->bits #(#f #t #t #f)))
  (test "vector->bits of four" 12 (vector->bits #(#f #f #t #t)))
  (test "bits" #b1110101 (bits #t #f #t #f #t #t #t))
  (test "bits, low zeros" #b111010100 (bits #f #f #t #f #t #f #t #t #t))
  (test "bits of none" 0 (bits))
  (test "list->bits inverts bits->list" (expt 3 50) (list->bits (bits->list (expt 3 50))))
  (test "and vector->bits inverts bits->vector" (expt 3 50) (vector->bits (bits->vector (expt 3 50)))))

(test-group "SRFI 151 - fold, unfold and generate"
  (test "bitwise-fold" '(#t #f #t #f #t #t #t) (bitwise-fold cons '() #b1010111))
  (test "bitwise-fold of 0 is the seed" 'seed (bitwise-fold cons 'seed 0))
  (test "bitwise-fold of a negative folds its integer-length bits" '(#f #f #t) (bitwise-fold cons '() -7))
  (test "bitwise-for-each, counting the set bits" 5
        (let ((count 0))
          (bitwise-for-each (lambda (b) (if b (set! count (+ count 1)))) #b1010111)
          count))
  (test "bitwise-for-each, in order from bit 0" '(#t #t #f #t)
        (let ((seen '()))
          (bitwise-for-each (lambda (b) (set! seen (cons b seen))) #b1011)
          (reverse seen)))
  (test "bitwise-unfold" #b101010101
        (bitwise-unfold (lambda (i) (= i 10)) even? (lambda (i) (+ i 1)) 0))
  (test "bitwise-unfold stopping at once" 0
        (bitwise-unfold (lambda (i) #t) even? (lambda (i) (+ i 1)) 0))
  (test "make-bitwise-generator" '(#f #t #t #f)
        (let ((g (make-bitwise-generator #b110)))
          (let* ((a (g)) (b (g)) (c (g)) (d (g))) (list a b c d))))
  (test "make-bitwise-generator, a negative's bits continue as 1s" '(#t #f #t #t #t)
        (let ((g (make-bitwise-generator -3)))
          (let* ((a (g)) (b (g)) (c (g)) (d (g)) (e (g))) (list a b c d e)))))

(test-group "SRFI 151 - argument checking"
  (test-error "bitwise-and refuses an inexact number" "bitwise-and" (bitwise-and 1 2.0))
  (test-error "bitwise-ior refuses a rational" "bitwise-ior" (bitwise-ior 1/2))
  (test-error "bitwise-xor refuses a non-number" "bitwise-xor" (bitwise-xor 1 'a))
  (test-error "bitwise-not refuses a non-integer" "bitwise-not" (bitwise-not 1.5))
  (test-error "bitwise-eqv refuses a non-integer" "bitwise-eqv" (bitwise-eqv 1 "2"))
  (test-error "bitwise-nand refuses a non-integer" "bitwise-nand" (bitwise-nand 1 #f))
  (test-error "arithmetic-shift refuses an inexact count" "arithmetic-shift" (arithmetic-shift 1 2.0))
  (test-error "bit-count refuses a non-integer" "bit-count" (bit-count 'x))
  (test-error "integer-length refuses a non-integer" "integer-length" (integer-length 0.5))
  (test-error "bit-set? refuses a negative index" "bit-set?" (bit-set? -1 5))
  (test-error "bit-set? refuses a non-integer" "bit-set?" (bit-set? 0 'x))
  (test-error "copy-bit refuses a non-boolean" "copy-bit" (copy-bit 0 1 'yes))
  (test-error "bit-field refuses an end before its start" "bit-field" (bit-field 6 3 2))
  (test-error "bit-field refuses a negative start" "bit-field" (bit-field 6 -1 2))
  (test-error "bit-field-rotate refuses a non-integer count" "bit-field-rotate" (bit-field-rotate 6 1.5 0 4))
  (test-error "bits->list refuses a negative integer" "bits->list" (bits->list -1))
  (test-error "bits->list refuses a negative length" "bits->list" (bits->list 5 -1))
  (test-error "list->bits refuses a non-boolean" "list->bits" (list->bits '(#t 1)))
  (test-error "vector->bits refuses a non-boolean" "vector->bits" (vector->bits #(#f 0)))
  (test-error "bitwise-fold refuses a non-procedure" "bitwise-fold" (bitwise-fold 1 '() 5)))
