;; SRFI 1: List library
;;
;; Most expected values are the examples from the SRFI 1 document itself. The
;; procedures SRFI 1 shares with R7RS-small are re-exported from (scheme base),
;; and are tested only where SRFI 1 says more than R7RS does.
;;
;; A linear-update procedure (`take!`, `filter!` and so on) is allowed to
;; destroy its argument but not required to, so only its result is checked,
;; and each is given a fresh list.

(import (scheme base)
        (srfi 1))

(test-group "SRFI 1 - constructors"
  (test "xcons" '(b . a) (xcons 'a 'b))
  (test "cons* with several arguments" '(1 2 3 . 4) (cons* 1 2 3 4))
  (test "cons* with one argument" 1 (cons* 1))
  (test "make-list with a fill" '(c c c) (make-list 3 'c))
  (test "list-tabulate" '(0 1 2 3) (list-tabulate 4 values))
  (test "list-tabulate applies the procedure to each index" '(0 1 4 9) (list-tabulate 4 (lambda (i) (* i i))))
  (test "list-copy copies the spine" #f (let ((l (list 1 2))) (eq? l (list-copy l))))
  (test "iota with a count" '(0 1 2 3 4) (iota 5))
  (test "iota with a start" '(1 2 3) (iota 3 1))
  (test "iota with a step" '(0 -1 -2 -3 -4) (iota 5 0 -1))
  (test "iota of zero" '() (iota 0))
  (test "circular-list repeats" '(z q z q z) (take (circular-list 'z 'q) 5))
  (test-error "iota rejects a negative count" "iota" (iota -1)))

(test-group "SRFI 1 - predicates"
  (test "proper-list? on a list" #t (proper-list? '(1 2)))
  (test "proper-list? on the empty list" #t (proper-list? '()))
  (test "proper-list? on a dotted list" #f (proper-list? '(1 . 2)))
  (test "proper-list? on a circular list" #f (proper-list? (circular-list 1 2)))
  (test "circular-list?" #t (circular-list? (circular-list 1)))
  (test "circular-list? on a proper list" #f (circular-list? '(1 2)))
  (test "dotted-list? on a dotted list" #t (dotted-list? '(1 . 2)))
  (test "dotted-list? on a non-pair" #t (dotted-list? 3))
  (test "dotted-list? on a proper list" #f (dotted-list? '(1)))
  (test "not-pair?" #t (not-pair? 3))
  (test "not-pair? on a pair" #f (not-pair? '(1)))
  (test "null-list? on the empty list" #t (null-list? '()))
  (test "null-list? on a pair" #f (null-list? '(1)))
  (test "list= of equal lists" #t (list= eq? '(a b) '(a b) '(a b)))
  (test "list= of unequal lists" #f (list= eq? '(a b) '(a c)))
  (test "list= of lists of different lengths" #f (list= eq? '(a) '(a b)))
  (test "list= with no lists" #t (list= eq?))
  (test "list= with one list" #t (list= eq? '(a))))

(test-group "SRFI 1 - selectors"
  (test "first" 1 (first '(1 2 3 4 5 6 7 8 9 10)))
  (test "fifth" 5 (fifth '(1 2 3 4 5 6 7 8 9 10)))
  (test "tenth" 10 (tenth '(1 2 3 4 5 6 7 8 9 10)))
  (test "car+cdr" '(1 (2)) (call-with-values (lambda () (car+cdr '(1 2))) list))
  (test "take" '(a b) (take '(a b c d e) 2))
  (test "drop" '(c d e) (drop '(a b c d e) 2))
  (test "take of a dotted list" '(1 2) (take '(1 2 3 . d) 2))
  (test "drop of a dotted list" '(3 . d) (drop '(1 2 3 . d) 2))
  (test "take-right" '(d e) (take-right '(a b c d e) 2))
  (test "drop-right" '(a b c) (drop-right '(a b c d e) 2))
  (test "take-right of a dotted list" '(2 3 . d) (take-right '(1 2 3 . d) 2))
  (test "drop-right of a dotted list" '(1) (drop-right '(1 2 3 . d) 2))
  (test "take-right of all of a dotted list" 'd (take-right '(1 2 3 . d) 0))
  (test "take!" '(1 2) (take! (list 1 2 3) 2))
  (test "drop-right!" '(1) (drop-right! (list 1 2 3) 2))
  (test "split-at" '((a b c) (d e f g h))
        (call-with-values (lambda () (split-at '(a b c d e f g h) 3)) list))
  (test "split-at!" '((a) (b c))
        (call-with-values (lambda () (split-at! (list 'a 'b 'c) 1)) list))
  (test "last" 'c (last '(a b c)))
  (test "last-pair" '(c) (last-pair '(a b c)))
  (test-error "take past the end" "take" (take '(1 2) 3))
  (test-error "last of the empty list" "last" (last '())))

(test-group "SRFI 1 - miscellaneous"
  (test "length+ of a proper list" 3 (length+ '(1 2 3)))
  (test "length+ of a circular list" #f (length+ (circular-list 1 2)))
  (test "concatenate" '(1 2 3 4) (concatenate '((1) (2 3) () (4))))
  (test "concatenate!" '(1 2 3) (concatenate! (list (list 1) (list 2 3))))
  (test "append!" '(1 2 3 4) (append! (list 1 2) (list 3) '() (list 4)))
  (test "append! with no arguments" '() (append!))
  (test "reverse!" '(3 2 1) (reverse! (list 1 2 3)))
  (test "append-reverse" '(3 2 1 4 5) (append-reverse '(1 2 3) '(4 5)))
  (test "append-reverse!" '(2 1 3) (append-reverse! (list 1 2) (list 3)))
  (test "zip" '((one 1 odd) (two 2 even) (three 3 odd))
        (zip '(one two three) '(1 2 3) '(odd even odd even odd even odd even)))
  (test "zip of one list" '((1) (2) (3)) (zip '(1 2 3)))
  (test "zip stops at a circular list's partner" '((3 #f) (1 #t) (4 #f) (1 #t))
        (zip '(3 1 4 1) (circular-list #f #t)))
  (test "unzip1" '(1 2) (unzip1 '((1 a) (2 b))))
  (test "unzip2" '((1 2 3) (one two three))
        (call-with-values (lambda () (unzip2 '((1 one) (2 two) (3 three)))) list))
  (test "unzip3" '((1 2) (a b) (x y))
        (call-with-values (lambda () (unzip3 '((1 a x) (2 b y)))) list))
  (test "unzip4" '((1) (2) (3) (4)) (call-with-values (lambda () (unzip4 '((1 2 3 4)))) list))
  (test "unzip5" '((1) (2) (3) (4) (5)) (call-with-values (lambda () (unzip5 '((1 2 3 4 5)))) list))
  (test "count" 3 (count even? '(3 1 4 1 5 9 2 5 6)))
  (test "count over two lists" 3 (count < '(1 2 4 8) '(2 4 6 8 10 12 14 16)))
  (test "count stops at the shorter, circular list" 2 (count < '(3 1 4 1) (circular-list 1 10))))

(test-group "SRFI 1 - fold, unfold and map"
  (test "fold sums" 10 (fold + 0 '(1 2 3 4)))
  (test "fold reverses" '(3 2 1) (fold cons '() '(1 2 3)))
  (test "fold counts" 2 (fold (lambda (x count) (if (symbol? x) (+ count 1) count)) 0 '(a 1 b 2)))
  (test "fold over two lists" '(c 3 b 2 a 1) (fold cons* '() '(a b c) '(1 2 3 4 5)))
  (test "fold-right copies" '(1 2 3) (fold-right cons '() '(1 2 3)))
  (test "fold-right filters" '(2 4) (fold-right (lambda (x l) (if (even? x) (cons x l) l)) '() '(1 2 3 4)))
  (test "fold-right over two lists" '(a 1 b 2 c 3) (fold-right cons* '() '(a b c) '(1 2 3 4 5)))
  (test "pair-fold" '((c) (b c) (a b c)) (pair-fold cons '() '(a b c)))
  (test "pair-fold-right" '((a b c) (b c) (c)) (pair-fold-right cons '() '(a b c)))
  (test "reduce" 10 (reduce + 0 '(1 2 3 4)))
  (test "reduce of the empty list" 0 (reduce + 0 '()))
  (test "reduce takes the maximum" 9 (reduce max 0 '(3 9 2)))
  (test "reduce-right appends" '(1 2 3 4 5) (reduce-right append '() '((1 2) (3) (4 5))))
  (test "unfold builds squares" '(1 4 9 16 25 36 49 64 81 100)
        (unfold (lambda (x) (> x 10)) (lambda (x) (* x x)) (lambda (x) (+ x 1)) 1))
  (test "unfold with a tail generator" '(1 2 . end)
        (unfold (lambda (x) (> x 2)) values (lambda (x) (+ x 1)) 1 (lambda (x) 'end)))
  (test "unfold-right builds squares" '(1 4 9 16 25 36 49 64 81 100)
        (unfold-right zero? (lambda (x) (* x x)) (lambda (x) (- x 1)) 10))
  (test "unfold-right with a tail" '(3 2 1 4 5)
        (unfold-right null-list? car cdr '(1 2 3) '(4 5)))
  (test "append-map" '(1 -1 3 -3 8 -8) (append-map (lambda (x) (list x (- x))) '(1 3 8)))
  (test "append-map over two lists" '(1 a 2 b) (append-map list '(1 2) '(a b)))
  (test "append-map!" '(1 -1 3 -3) (append-map! (lambda (x) (list x (- x))) '(1 3)))
  (test "pair-for-each" '((c) (b c) (a b c))
        (let ((seen '())) (pair-for-each (lambda (p) (set! seen (cons p seen))) '(a b c)) seen))
  (test "filter-map" '(1 9 49)
        (filter-map (lambda (x) (and (number? x) (* x x))) '(a 1 b 3 c 7)))
  (test "filter-map over two lists" '(7) (filter-map (lambda (a b) (and (> b 2) (+ a b))) '(1 2 3) '(1 2 4)))
  (test "map-in-order applies in order" '(1 2 3)
        (let ((order '())) (map-in-order (lambda (x) (set! order (cons x order)) x) '(1 2 3)) (reverse order)))
  (test "map-in-order over two lists" '(5 7 9) (map-in-order + '(1 2 3) '(4 5 6)))
  (test "map!" '(2 3 4) (map! (lambda (x) (+ x 1)) (list 1 2 3)))
  (test "map stops at the shorter list" '(4 1 5 1) (map + '(3 1 4 1) (circular-list 1 0))))

(test-group "SRFI 1 - filtering and partitioning"
  (test "filter" '(0 8 8 -4) (filter even? '(0 7 8 8 43 -4)))
  (test "remove" '(7 43) (remove even? '(0 7 8 8 43 -4)))
  (test "partition" '((one four five) (2 3 6))
        (call-with-values (lambda () (partition symbol? '(one 2 3 four five 6))) list))
  (test "filter!" '(2 4) (filter! even? (list 1 2 3 4)))
  (test "remove!" '(1 3) (remove! even? (list 1 2 3 4)))
  (test "partition!" '((2) (1 3)) (call-with-values (lambda () (partition! even? (list 1 2 3))) list)))

(test-group "SRFI 1 - searching"
  (test "find" 4 (find even? '(3 1 4 1 5 9)))
  (test "find with no match" #f (find even? '(1 3)))
  (test "find-tail" '(-8 -5 0 0) (find-tail even? '(3 1 37 -8 -5 0 0)))
  (test "find-tail with no match" #f (find-tail even? '(3 1 37 -5)))
  (test "any" #t (any integer? '(a 3 b 2.7)))
  (test "any returns the predicate's value" 3 (any (lambda (x) (and (number? x) x)) '(a 3 b)))
  (test "any with no match" #f (any integer? '(a 3.1 b 2.7)))
  (test "any over two lists" #t (any < '(3 1 4 1 5) '(2 7 1 8 2)))
  (test "any of the empty list" #f (any even? '()))
  (test "every" #t (every integer? '(1 2 3)))
  (test "every returns the last value" 3 (every (lambda (x) (and (number? x) x)) '(1 2 3)))
  (test "every of the empty list" #t (every even? '()))
  (test "every over two lists" #f (every < '(1 2) '(2 1)))
  (test "list-index" 2 (list-index even? '(3 1 4 1 5 9)))
  (test "list-index over two lists" 1 (list-index < '(3 1 4 1 5 9 2 5 6) '(2 7 1 8 2)))
  (test "list-index with no match" #f (list-index = '(3 1 4 1 5 9 2 5 6) '(2 7 1 8 2)))
  (test "take-while" '(2 18) (take-while even? '(2 18 3 10 22 9)))
  (test "drop-while" '(3 10 22 9) (drop-while even? '(2 18 3 10 22 9)))
  (test "take-while!" '(2) (take-while! even? (list 2 3 4)))
  (test "span" '((2 18) (3 10 22 9))
        (call-with-values (lambda () (span even? '(2 18 3 10 22 9))) list))
  (test "break" '((3 1) (4 1 5 9 2 6))
        (call-with-values (lambda () (break even? '(3 1 4 1 5 9 2 6))) list))
  (test "span!" '((2) (3)) (call-with-values (lambda () (span! even? (list 2 3))) list))
  (test "break!" '((3) (2)) (call-with-values (lambda () (break! even? (list 3 2))) list))
  (test "member with a comparison" '(3 4) (member 2.5 '(1 2 3 4) <)))

(test-group "SRFI 1 - deletion"
  (test "delete" '(1 3) (delete 2 '(1 2 3 2)))
  (test "delete with a comparison" '(1 2) (delete 5 '(1 7 2 9) <))
  (test "delete!" '(a c) (delete! 'b (list 'a 'b 'c)))
  (test "delete-duplicates" '(a b c z) (delete-duplicates '(a b a c a b c z)))
  (test "delete-duplicates keeps the first of each" '((a . 3) (b . 7) (c . 1))
        (delete-duplicates '((a . 3) (b . 7) (a . 9) (c . 1))
                           (lambda (x y) (eq? (car x) (car y)))))
  (test "delete-duplicates!" '(1 2) (delete-duplicates! (list 1 2 1 2))))

(test-group "SRFI 1 - association lists"
  (test "alist-cons" '((a . 1) (b . 2)) (alist-cons 'a 1 '((b . 2))))
  (test "alist-copy copies each association" #f
        (let ((a (list (cons 'a 1)))) (eq? (car a) (car (alist-copy a)))))
  (test "alist-delete" '((b . 2)) (alist-delete 'a '((a . 1) (b . 2) (a . 3))))
  (test "alist-delete with a comparison" '((5 . x)) (alist-delete 3 '((1 . y) (5 . x)) >))
  (test "alist-delete!" '((b . 2)) (alist-delete! 'a (list (cons 'a 1) (cons 'b 2))))
  (test "assoc with a comparison" '(3 . c) (assoc 2.5 '((1 . a) (3 . c)) <)))

(test-group "SRFI 1 - lists as sets"
  (test "lset<=" #t (lset<= eq? '(a) '(a b a) '(a b c c)))
  (test "lset<= with no lists" #t (lset<= eq?))
  (test "lset<= failing" #f (lset<= eq? '(a d) '(a b)))
  (test "lset=" #t (lset= eq? '(b e a) '(a e b) '(e e b a)))
  (test "lset= failing" #f (lset= eq? '(a) '(a b)))
  (test "lset-adjoin" '(u o i a b c d c e) (lset-adjoin eq? '(a b c d c e) 'a 'e 'i 'o 'u))
  (test "lset-union" '(u o i a b c d e) (lset-union eq? '(a b c d e) '(a e i o u)))
  (test "lset-union keeps duplicates of the first list" '(x a a c) (lset-union eq? '(a a c) '(x a x)))
  (test "lset-union of nothing" '() (lset-union eq?))
  (test "lset-union of one list" '(a b c) (lset-union eq? '(a b c)))
  (test "lset-intersection" '(a e) (lset-intersection eq? '(a b c d e) '(a e i o u)))
  (test "lset-intersection keeps duplicates" '(a x a) (lset-intersection eq? '(a x y a) '(x a x z)))
  (test "lset-difference" '(b c d) (lset-difference eq? '(a b c d e) '(a e i o u)))
  (test "lset-difference of one list" '(a b c) (lset-difference eq? '(a b c)))
  ;; The order of a result is unspecified, so lset-xor's is compared as a set.
  (test "lset-xor" #t (lset= eq? '(d c b i o u) (lset-xor eq? '(a b c d e) '(a e i o u))))
  (test "lset-xor of nothing" '() (lset-xor eq?))
  (test "lset-diff+intersection" '((b c d) (a e))
        (call-with-values (lambda () (lset-diff+intersection eq? '(a b c d e) '(a e i o u))) list))
  (test "lset-union!" '(u o i a b c d e) (lset-union! eq? (list 'a 'b 'c 'd 'e) (list 'a 'e 'i 'o 'u)))
  (test "lset-intersection!" '(a e) (lset-intersection! eq? (list 'a 'b 'c 'd 'e) '(a e i o u)))
  (test "lset-difference!" '(b c d) (lset-difference! eq? (list 'a 'b 'c 'd 'e) '(a e i o u)))
  (test "lset-xor!" #t (lset= eq? '(d c b i o u) (lset-xor! eq? (list 'a 'b 'c 'd 'e) (list 'a 'e 'i 'o 'u))))
  (test "lset-diff+intersection!" '((b) (a))
        (call-with-values (lambda () (lset-diff+intersection! eq? (list 'a 'b) '(a))) list)))

(test-group "SRFI 1 - argument checking"
  (test-error "fold rejects a non-procedure" "fold" (fold 1 0 '(1 2)))
  (test-error "filter rejects a non-procedure" "filter" (filter 1 '(1 2)))
  (test-error "list-tabulate rejects a negative count" "list-tabulate" (list-tabulate -1 values))
  (test-error "drop past the end" "drop" (drop '(1 2) 3)))
