/**
 * @fileoverview Rendering a table of compiled procedures as a module.
 *
 * Two build steps write one of these -- the standard library's and the
 * compiler's own -- and `installPrebuilt` reads both. One renderer rather than
 * two keeps the shape it reads and the shape they write the same thing.
 */

/**
 * Renders a procedure's constant pool as a JavaScript expression, or reports
 * that it cannot be.
 *
 * ## Why a pool exists at all
 *
 * The emitter writes immediates straight into the generated source and interns
 * everything else -- symbols, pairs, vectors -- because those have identity
 * that `eq?` can observe, so re-creating one per evaluation would be wrong as
 * well as slow. The pool is built once and handed to the procedure's factory.
 *
 * ## Why only symbols, so far
 *
 * A symbol is the one interned value that survives being written down. Writing
 * `intern("lambda")` and reading it back yields *the same object*, so the
 * identity the pool exists to preserve is preserved by reconstructing it. A
 * pair is not like that: two reconstructions are two pairs, and a procedure
 * that compared them with `eq?` would see a difference the interpreter never
 * shows it.
 *
 * Pairs could be serialized -- built once at module scope, shared the way the
 * factory shares them -- and when a procedure needs it, that is the work to do.
 * Until then a procedure whose pool holds one is left out and stays
 * interpreted, which is the same answer this gave before it could serialize
 * anything, and correct rather than merely safe.
 *
 * @param {Array<*>} constants - A procedure's constant pool.
 * @returns {string|null} A JavaScript array expression, or null if some value
 *   in the pool cannot be written down.
 */
export function serializeConstants(constants) {
  const parts = [];
  for (const value of constants) {
    if (value !== null && typeof value === 'object'
      && value.constructor && value.constructor.name === 'Symbol'
      && typeof value.name === 'string') {
      parts.push(`intern(${JSON.stringify(value.name)})`);
      continue;
    }
    return null;
  }
  return `[${parts.join(', ')}]`;
}

/**
 * Renders a generated prebuilt table as JavaScript module text.
 *
 * @param {Object} table - What to render.
 * @param {string} table.generator - The script writing it, for the banner.
 * @param {string} table.title - One line saying what the table holds.
 * @param {string} table.fingerprint - Fingerprint of the sources compiled from.
 * @param {string} table.filesName - Name to export the file list under.
 * @param {string[]} table.files - The sources, in the order the fingerprint
 *   covers them.
 * @param {Array<Object>} table.entries - Entries from `generateEnvironment`.
 * @returns {string} JavaScript module text.
 */
export function renderTable(table) {
  const entries = table.entries.map((entry) => {
    // The generated source is a function *body*: it declares the procedure,
    // marks it, and returns it. Wrapping it in an arrow makes it a value the
    // module can export, with no `new Function` anywhere.
    const body = entry.source.split('\n').map((line) => '    ' + line).join('\n');
    return `  ${JSON.stringify(entry.name)}: {\n`
      + `    params: ${JSON.stringify(entry.params)},\n`
      + `    rest: ${JSON.stringify(entry.rest ?? null)},\n`
      + `    constants: ${serializeConstants(entry.constants)},\n`
      + `    make: (R, E, K) => {\n${body}\n    }\n`
      + `  }`;
  });

  // Imported only when something needs it, so a table of procedures with no
  // pooled constants stays a module with no dependencies.
  const needsIntern = table.entries.some((entry) => entry.constants.length > 0);

  return `// Auto-generated by ${table.generator} - do not edit manually
//
// ${table.title}
//
// Each entry holds the JavaScript the compiler would otherwise generate at
// startup, as a factory taking the runtime, the environment its globals resolve
// in, and its constant pool.
//
// \`FINGERPRINT\` is of the sources this was generated from. \`installPrebuilt\` in
// src/compiler/prebuilt.js recomputes it and installs nothing if it differs, so
// a stale build leaves those procedures interpreted rather than running code
// for source that has since changed.
${needsIntern ? "\nimport { intern } from '../core/interpreter/symbol.js';\n" : ''}
/** @type {string} Fingerprint of the sources this was generated from. */
export const FINGERPRINT = ${JSON.stringify(table.fingerprint)};

/** @type {string[]} The sources, in the order the fingerprint covers them. */
export const ${table.filesName} = ${JSON.stringify(table.files, null, 2)};

/** @type {Object<string, {params: string[], rest: (string|null), constants: Array<*>, make: Function}>} */
export const PROCEDURES = {
${entries.join(',\n')}
};

export default { fingerprint: FINGERPRINT, files: ${table.filesName}, procedures: PROCEDURES };
`;
}
