;; pin_seed.scm -- pins the seed: writes src/packaging/pinned_seed.js, the
;; libraries the reader and the expander are made of -- (scheme-js
;; special-forms), (scheme core), (scheme control), (scheme-js reader) and
;; (scheme-js expander) -- as their core forms: each library's
;; `define-library` form, and every top-level form loading it ran, in order,
;; as the core form the expander made of it, a macro's definition as one that
;; binds it pending.
;;
;; Run, interpreted, they make a reader and an expander with no text read, no
;; form expanded and no prebuilt table: what the library system's seed reads
;; and expands its own libraries with when one of their tables is not current
;; (src/core/interpreter/library_seed.js), and so what the build can always
;; rebuild them from. Run on purpose, with a reader and an expander known to
;; work -- `npm run pin:seed` -- and committed; the build never writes it.
;;
;;     node repl.js -I scripts/lib scripts/pin_seed.scm

(import (scheme base)
        (scheme file)
        (srfi 1)
        (srfi 152)
        (scheme-js compiler build)
        (scheme-js prebuild)
        (scheme-js table-writer))

;; /**
;;  * Where the libraries' files live.
;;  */
(define library-dirs '("src/core/scheme" "src/extras/scheme"))

;; /**
;;  * The module written.
;;  */
(define output "src/packaging/pinned_seed.js")

;; /**
;;  * The libraries pinned, in the order they need each other.
;;  */
(define pinned '((scheme-js special-forms) (scheme core) (scheme control) (scheme-js reader)
                 (scheme-js expander)))

(define read-source (source-reader library-dirs))

;; /**
;;  * A datum as the JSON text the seed reads it from, as a JavaScript string
;;  * literal.
;;  * @param {*} datum - The datum, which can be written down.
;;  * @returns {string}
;;  */
(define (json-literal datum)
  (json-string (json-datum datum)))

;; /**
;;  * A pinned library's entry: its `define-library` form, and each form its
;;  * loading ran as the core form it expanded into.
;;  * @param {list} name - The library's name, as symbols.
;;  * @param {list} forms - The forms its loading ran, `(form . core)`.
;;  * @returns {string} The entry's text.
;;  */
(define (library-entry name forms)
  (let* ((strings (map symbol->string name))
         (key (library-key strings))
         ;; Nothing restored, so that every form is held as its core form.
         (restore (restore-sequence forms (lambda (name form) #f))))
    (if (not (restore-writable? restore))
        (error "a form a pinned library runs cannot be written down" key))
    (string-append
     "  " (json-string key) ": {\n"
     "    declaration: " (json-literal (library-declaration read-source strings)) ",\n"
     "    items: [\n"
     (string-join (map (lambda (item)
                         (if (not (eq? (car item) 'core))
                             (error "a form a pinned library runs expands into a core form that cannot be written down" key))
                         (string-append "      " (json-literal (cadr item))))
                       restore)
                  ",\n")
     "\n    ]\n  }")))

;; Loaded from source, in a registry of their own with nothing restored, each
;; form noted with its core form as it is expanded.
(define noted '())

(with-private-libraries
 (library-resolver read-source)
 (lambda (name env) (set! noted (cons (cons (map string->symbol name) (take-noted!)) noted)))
 (lambda () (for-each (lambda (name) (load-library name note!)) pinned)))

(let ((entries (map (lambda (name) (library-entry name (cdr (assoc name noted)))) pinned)))
  (call-with-output-file output
    (lambda (port)
      (write-string
       (string-append
        "// Auto-generated by scripts/pin_seed.scm -- regenerate on purpose, never by the build.\n"
        "//\n"
        "// The libraries the reader and the expander are made of, as core forms: each\n"
        "// library's `define-library` form, and every top-level form loading it ran,\n"
        "// in order, as the core form it expanded into. Run, interpreted, they make a\n"
        "// reader and an expander with no text read, no form expanded and no prebuilt\n"
        "// table, which the library system's seed reads and expands its own libraries\n"
        "// with when one of their tables is not current\n"
        "// (src/core/interpreter/library_seed.js). Each form is JSON text, made into\n"
        "// data only when the seed asks (`decodeDatum` in src/compiler/prebuilt.js),\n"
        "// which a start with its tables current never does.\n"
        "\n"
        "export default function pinnedSeedImage() {\n"
        "  return {\n"
        (string-join entries ",\n")
        "\n  };\n"
        "}\n")
       port)))
  (say "Pinned the seed -> " output))
