/**
 * @fileoverview Pins the seed: writes `src/packaging/pinned_seed.js`, the
 * libraries the reader and the expander are made of -- `(scheme core)`,
 * `(scheme control)`, `(scheme-js reader)` and `(scheme-js expander)` -- as
 * their core forms: each library's `define-library` form, and every top-level
 * form loading it ran, in order, as the core form the expander made of it, a
 * macro's definition as one that binds it pending.
 *
 * Run, interpreted, they make a reader and an expander with no text read, no
 * form expanded and no prebuilt table: what the library system's seed reads
 * and expands its own libraries with when one of their tables is not current
 * (`library_seed.js`), and so what the build can always rebuild them from.
 * Run on purpose, with a reader and an expander known to work -- `npm run
 * pin:seed` -- and committed; the build never writes it.
 *
 * Usage: node scripts/pin_seed.js
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { createInterpreter } from '../src/core/interpreter/index.js';
import { parse } from '../src/core/interpreter/reader.js';
import { BUNDLED_SOURCES } from '../src/packaging/bundled_libraries.js';
import {
  setFileResolver, setLibraryLoadHook, loadLibrarySync, registerBuiltinLibrary, createPrimitiveExports
} from '../src/core/interpreter/library_loader.js';
import { withPrivateLibraries, libraryNameToKey } from '../src/core/interpreter/library_registry.js';
import { tableWriter, notingExpander } from './lib/table_writer.js';
import { toArray } from '../src/core/interpreter/cons.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = path.join(ROOT, 'src/packaging/pinned_seed.js');

/** The libraries pinned, in the order they need each other. */
const LIBRARIES = [['scheme', 'core'], ['scheme', 'control'], ['scheme-js', 'reader'], ['scheme-js', 'expander']];

/**
 * A library's file, or a file it includes, from the bundled sources.
 * @param {string[]} name - The library's name, or the include's path.
 * @returns {string} Its text.
 */
function bundled(name) {
  const last = name[name.length - 1];
  const text = BUNDLED_SOURCES[`${last}.sld`] ?? BUNDLED_SOURCES[last];
  if (text === undefined) throw new Error(`no bundled source for ${name.join('/')}`);
  return text;
}

const scratch = createInterpreter();
setFileResolver(bundled);
const writer = tableWriter(scratch.interpreter, scratch.env);

// Loaded from source, in a registry of their own with nothing restored, each
// form noted with its core form as it is expanded.
const noting = notingExpander();
const noted = new Map();
withPrivateLibraries({ resolver: bundled }, () => {
  const { interpreter, env } = createInterpreter();
  registerBuiltinLibrary(['scheme', 'primitives'], createPrimitiveExports(env), env);
  setLibraryLoadHook((name) => noted.set(libraryNameToKey(name), noting.take()));
  try {
    for (const name of LIBRARIES) loadLibrarySync(name, noting.analyze, interpreter, env);
  } finally {
    setLibraryLoadHook(null);
  }
});

const entries = LIBRARIES.map((name) => {
  const key = libraryNameToKey(name);
  const declaration = parse(bundled(name), { filename: name.join('/'), dotAccess: false })[0];
  const { restore } = writer.restoring(noted.get(key), scratch.env, []);
  if (restore === false) throw new Error(`a form ${key} runs cannot be written down`);
  const items = toArray(restore).map((item) => {
    const [kind, value] = toArray(item);
    if (kind.name !== 'core') throw new Error(`a form ${key} runs expands into a core form that cannot be written down`);
    return `      ${JSON.stringify(writer.json(value))}`;
  });
  return `  ${JSON.stringify(key)}: {\n`
    + `    declaration: ${JSON.stringify(writer.json(declaration))},\n`
    + `    items: [\n${items.join(',\n')}\n    ]\n  }`;
});

fs.writeFileSync(OUTPUT, `// Auto-generated by scripts/pin_seed.js -- regenerate on purpose, never by the build.
//
// The libraries the reader and the expander are made of, as core forms: each
// library's \`define-library\` form, and every top-level form loading it ran,
// in order, as the core form it expanded into. Run, interpreted, they make a
// reader and an expander with no text read, no form expanded and no prebuilt
// table, which the library system's seed reads and expands its own libraries
// with when one of their tables is not current
// (src/core/interpreter/library_seed.js). Each form is JSON text, made into
// data only when the seed asks (\`decodeDatum\` in src/compiler/prebuilt.js),
// which a start with its tables current never does.

export default function pinnedSeedImage() {
  return {
${entries.join(',\n')}
  };
}
`, 'utf8');
console.log(`Pinned the seed -> ${path.relative(ROOT, OUTPUT)}`);
