/**
 * @fileoverview Pins the reader: writes `src/packaging/pinned_reader.js`, the
 * sources of the libraries the reader is made of -- `(scheme core)`,
 * `(scheme control)` and `(scheme-js reader)` -- as data, each library's
 * `define-library` form and the forms of each file it includes.
 *
 * Evaluated, interpreted, they make a reader with no text read and no
 * prebuilt table: what the library system's seed reads with when a table of
 * one of its own libraries is not current (`library_seed.js`), and so what
 * the build can always rebuild the reader from. Run on purpose, with a reader
 * known to work -- `npm run pin:reader` -- and committed; the build never
 * writes it.
 *
 * Usage: node scripts/pin_reader.js
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { createInterpreter } from '../src/core/interpreter/index.js';
import { parse } from '../src/core/interpreter/reader.js';
import { BUNDLED_SOURCES } from '../src/packaging/bundled_libraries.js';
import { parseDefineLibrary, setFileResolver } from '../src/core/interpreter/library_loader.js';
import { tableWriter } from './lib/table_writer.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = path.join(ROOT, 'src/packaging/pinned_reader.js');

/** The libraries the reader is made of, in the order they need each other. */
const LIBRARIES = [['scheme', 'core'], ['scheme', 'control'], ['scheme-js', 'reader']];

/**
 * A library's file, from the bundled sources.
 * @param {string} file - Its name.
 * @returns {string} Its text.
 */
function sourceOf(file) {
  const text = BUNDLED_SOURCES[file];
  if (typeof text !== 'string') throw new Error(`no bundled source ${file}`);
  return text;
}

/**
 * JavaScript that rebuilds a datum.
 * @param {Object} writer - The table writer.
 * @param {*} datum - The datum.
 * @param {string} where - What it is, for an error.
 * @returns {string}
 */
function written(writer, datum, where) {
  const text = writer.datum(datum);
  if (text === null) throw new Error(`a datum in ${where} cannot be written down`);
  return text;
}

const scratch = createInterpreter();
setFileResolver((name) => {
  const last = name[name.length - 1];
  const text = BUNDLED_SOURCES[`${last}.sld`] ?? BUNDLED_SOURCES[last];
  if (text === undefined) throw new Error(`no bundled source for ${name.join('/')}`);
  return text;
});
const writer = tableWriter(scratch.interpreter, scratch.env);

const entries = LIBRARIES.map((name) => {
  const sld = `${name[name.length - 1]}.sld`;
  const declaration = parse(sourceOf(sld), { filename: name.join('/'), dotAccess: false })[0];
  const { includes } = parseDefineLibrary(declaration);
  const files = includes.map((file) =>
    `      ${JSON.stringify(file)}: [\n`
    + parse(sourceOf(file), { filename: file, dotAccess: false })
      .map((form) => `        ${written(writer, form, file)}`).join(',\n')
    + '\n      ]');
  return `  ${JSON.stringify(name.join('.'))}: {\n`
    + `    declaration: ${written(writer, declaration, sld)},\n`
    + `    files: {\n${files.join(',\n')}\n    }\n  }`;
});

fs.writeFileSync(OUTPUT, `// Auto-generated by scripts/pin_reader.js -- regenerate on purpose, never by the build.
//
// The sources of the libraries the reader is made of, as data: each library's
// \`define-library\` form, and the forms of each file it includes. Evaluated,
// interpreted, they make a reader with no text read and no prebuilt table,
// which the library system's seed reads with when one of its own libraries'
// tables is not current (src/core/interpreter/library_seed.js). Made when
// asked for, rather than as the module loads, since a start with its tables
// current never asks.

import { intern } from '../core/interpreter/symbol.js';
import { Cons } from '../core/interpreter/cons.js';
import { Char } from '../core/primitives/char_class.js';

export default function pinnedReaderSources() {
  return {
${entries.join(',\n')}
  };
}
`, 'utf8');
console.log(`Pinned the reader -> ${path.relative(ROOT, OUTPUT)}`);
