;; R7RS Compliance Tests - Section 6.6: Characters
;; Adapted from Chibi Scheme's R7RS test suite by Alex Shinn

(test-group "6.6 Characters"

  (test #t (char? #\a))
  ;; Type disjointness: strings are not characters
  (test #f (char? "a"))
  (test #f (char? 'a))
  (test #f (char? 0))

  (test #t (char=? #\a #\a #\a))
  (test #f (char=? #\a #\A))
  (test #t (char<? #\a #\b #\c))
  (test #f (char<? #\a #\a))
  (test #f (char<? #\b #\a))
  (test #f (char>? #\a #\b))
  (test #f (char>? #\a #\a))
  (test #t (char>? #\c #\b #\a))
  (test #t (char<=? #\a #\b #\b))
  (test #t (char<=? #\a #\a))
  (test #f (char<=? #\b #\a))
  (test #f (char>=? #\a #\b))
  (test #t (char>=? #\a #\a))
  (test #t (char>=? #\b #\b #\a))

  (test #t (char-ci=? #\a #\a))
  (test #t (char-ci=? #\a #\A #\a))
  (test #f (char-ci=? #\a #\b))
  (test #t (char-ci<? #\a #\B #\c))
  (test #f (char-ci<? #\A #\a))
  (test #f (char-ci<? #\b #\A))
  (test #f (char-ci>? #\A #\b))
  (test #f (char-ci>? #\a #\A))
  (test #t (char-ci>? #\c #\B #\a))
  (test #t (char-ci<=? #\a #\B #\b))
  (test #t (char-ci<=? #\A #\a))
  (test #f (char-ci<=? #\b #\A))
  (test #f (char-ci>=? #\A #\b))
  (test #t (char-ci>=? #\a #\A))
  (test #t (char-ci>=? #\b #\B #\a))

  (test #t (char-alphabetic? #\a))
  (test #f (char-alphabetic? #\space))
  (test #t (char-numeric? #\0))
  (test #f (char-numeric? #\.))
  (test #f (char-numeric? #\a))
  (test #t (char-whitespace? #\space))
  (test #t (char-whitespace? #\tab))
  (test #t (char-whitespace? #\newline))
  (test #f (char-whitespace? #\_))
  (test #f (char-whitespace? #\a))
  (test #t (char-upper-case? #\A))
  (test #f (char-upper-case? #\a))
  (test #f (char-upper-case? #\3))
  (test #t (char-lower-case? #\a))
  (test #f (char-lower-case? #\A))
  (test #f (char-lower-case? #\3))

  (test 0 (digit-value #\0))
  (test 3 (digit-value #\3))
  (test 9 (digit-value #\9))
  (test #f (digit-value #\.))
  (test #f (digit-value #\-))

  (test 97 (char->integer #\a))
  (test #\a (integer->char 97))

  (test #\A (char-upcase #\a))
  (test #\A (char-upcase #\A))
  (test #\a (char-downcase #\a))
  (test #\a (char-downcase #\A))
  (test #\a (char-foldcase #\a))
  (test #\a (char-foldcase #\A))
)
