;; The prebuilt tables' writer (scripts/lib/table_writer.scm): constants
;; written as JavaScript that rebuilds them, and a table of compiled
;; procedures written as a module.

(import (scheme base)
        (only (srfi 152) string-contains)
        (scheme-js table-writer))

(test-group "table writer - strings as JSON"
  (test "plain" "\"abc\"" (json-string "abc"))
  (test "a quote and a backslash" "\"a\\\"b\\\\c\"" (json-string "a\"b\\c"))
  (test "the short escapes" "\"\\b\\f\\n\\r\\t\""
        (json-string (string (integer->char 8) (integer->char 12) #\newline #\return #\tab)))
  (test "another control character, in hex" "\"\\u0001\\u001f\"" (json-string (string (integer->char 1) (integer->char 31))))
  (test "anything else as it is" "\"λ\x7f;\"" (json-string "λ\x7f;"))
  (test "a list of strings" "[\"a\",\"b\"]" (json-strings '("a" "b")))
  (test "an empty list of strings" "[]" (json-strings '())))

(test-group "table writer - constants"
  (test "the empty list" "null" (constant-expression '()))
  (test "booleans" '("true" "false") (list (constant-expression #t) (constant-expression #f)))
  (test "an exact integer" "42n" (constant-expression 42))
  (test "a negative one" "-7n" (constant-expression -7))
  (test "a big one" "123456789012345678901234567890n" (constant-expression 123456789012345678901234567890))
  (test "an inexact real" "1.5" (constant-expression 1.5))
  (test "a string" "\"hi\"" (constant-expression "hi"))
  (test "a symbol, interned" "intern(\"car\")" (constant-expression 'car))
  (test "a character, by code point" "new Char(97)" (constant-expression #\a))
  (test "a list" "new Cons(intern(\"a\"), new Cons(1n, null))" (constant-expression '(a 1)))
  (test "a dotted pair" "new Cons(\"x\", true)" (constant-expression (cons "x" #t)))
  (test "a vector, as an array" "[1n]" (constant-expression (vector 1)))
  (test "and inside a list" "new Cons(1n, new Cons([2n], null))" (constant-expression (list 1 (vector 2))))
  (test "an infinity, and its negation" '("Infinity" "-Infinity") (list (constant-expression (/ 1. 0.)) (constant-expression (/ -1. 0.))))
  (test "a procedure cannot be written down" #f (constant-expression car))
  (test "nor anything holding one" #f (constant-expression (list 1 (vector car))))
  (test "a pool" "[intern(\"a\"), 2n]" (constants-expression '(a 2)))
  (test "an empty pool" "[]" (constants-expression '()))
  (test "a pool with something that cannot be written down" #f (constants-expression (list 'a car))))

(test-group "table writer - a module"
  (define text
    (render-tables "scripts/test.js" "Some tables." "abcd1234"
                   (list (list "test.lib" "f00dfeed" '("lib.sld" "lib.scm")
                               (list (list "f" '("x_$1") #f '(a) "line one\nline two" #f)
                                     (list "g" '() "rest_$2" '() "body" #f))
                               #f #f))))
  (define (has? fragment) (and (string-contains text fragment) #t))
  (test "the banner names the generator" #t (has? "// Auto-generated by scripts/test.js - do not edit manually\n//\n// Some tables.\n"))
  (test "imports what the constants need, and no more" '(#t #f #f)
        (list (has? "import { intern } from '../core/interpreter/symbol.js';")
              (has? "import { Cons }")
              (has? "import { Char }")))
  (test "a table's fingerprint, runtime and files" #t
        (has? "  \"test.lib\": {\n    fingerprint: \"f00dfeed\",\n    runtime: \"abcd1234\",\n    files: [\"lib.sld\",\"lib.scm\"],\n    procedures: {\n"))
  (test "an entry, its body indented" #t
        (has? "      \"f\": {\n        params: [\"x_$1\"],\n        rest: null,\n        constants: [intern(\"a\")],\n        make: (R, E, K) => {\n        line one\n        line two\n        }\n      },\n"))
  (test "a rest parameter" #t (has? "        rest: \"rest_$2\",\n"))
  (test "the exports" #t (has? "export const LIBRARIES = {\n") )
  (test "and the default" #t (has? "\nexport default LIBRARIES;\n")))

(test-group "table writer - what restores a library"
  (test "a procedure's definition names it" 'f (procedure-definition-name '(define (f x) x)))
  (test "with no parameters" 'f (procedure-definition-name '(define (f) 1)))
  (test "a lambda's" 'g (procedure-definition-name '(define g (lambda (y) y))))
  (test "a case-lambda's" 'h (procedure-definition-name '(define h (case-lambda ((a) a)))))
  (test "a value's does not" #f (procedure-definition-name '(define x 1)))
  (test "nor a call's" #f (procedure-definition-name '(define p (make-parameter 1))))
  (test "nor a lambda's with more after it" #f (procedure-definition-name '(define g (lambda (y) y) 2)))
  (test "nor a macro's" #f (procedure-definition-name '(define-syntax m (syntax-rules () ((_ x) x)))))
  (test "nor a record type's" #f (procedure-definition-name '(define-record-type point (make-point x) point?)))
  (test "nor an expression" #f (procedure-definition-name '(display 1)))
  (test "a macro's definition names it" 'm (macro-definition-name '(define-syntax m (syntax-rules () ((_ x) x)))))
  (test "a define-macro's" 'n (macro-definition-name '(define-macro (n x) x)))
  (test "a procedure's does not" #f (macro-definition-name '(define (f x) x)))
  (test "a library's forms, in order, a procedure by name where it made the final binding, else its core form"
        '((procedure f) (core (define x (app (var f) ()))) (core (define g (lambda () #f "g" (lit 1) () #f)))
          (procedure g))
        (restore-sequence '(((define (f) 1) . (define f (lambda () #f "f" (lit 1) () #f)))
                            ((define x (f)) . (define x (app (var f) ())))
                            ((define (g) 1) . (define g (lambda () #f "g" (lit 1) () #f)))
                            ((define (g) 2) . (define g (lambda () #f "g" (lit 2) () #f))))
                          (lambda (name form) (or (eq? name 'f) (equal? form '(define (g) 2))))))
  (test "a macro's definition, as one that binds it pending"
        '((core (define-syntax m (define-syntax m (syntax-rules () ((_ x) x))))))
        (restore-sequence '(((define-syntax m (syntax-rules () ((_ x) x))) . (lit ())))
                          (lambda (name form) #f)))
  (test "a form whose core form cannot be written down, as itself"
        (list (list 'form '(f)))
        (restore-sequence (list (cons '(f) (list 'app (list 'lit (lambda () 1)) '())))
                          (lambda (name form) #f))))

(test-group "table writer - a module that restores its libraries"
  (define text
    (render-tables "scripts/test.js" "Some tables." "abcd1234"
                   (list (list "test.lib" "f00dfeed" '("lib.sld")
                               (list (list "f" '() #f '() "body" "{\"line\":1}"))
                               '((procedure f) (core (define-syntax m (define-syntax m (syntax-rules () ((_ x) x)))))
                                 (form (g)))
                               '(define-library (test lib) (export f)))
                         (list "test.other" "0ddba11" '("other.sld")
                               (list (list "g" '() #f '() "body" #f))
                               #f #f))))
  (define (has? fragment) (and (string-contains text fragment) #t))
  (test "a restorable procedure's span" #t (has? "        span: {\"line\":1},\n        make: (R, E, K) => {\n"))
  (test "the forms loading runs, in order" #t
        (has? "    restore: [\n      {procedure: \"f\"},\n      {core: new Cons(intern(\"define-syntax\"), new Cons(intern(\"m\"), "))
  (test "and a form to expand" #t (has? "      {form: new Cons(intern(\"g\"), null)}\n"))
  (test "the procedures, then the forms" #t (has? "        }\n      }\n    },\n    restore: [\n"))
  (test "a library's define-library form, which the library system's seed reads instead of its .sld" #t
        (has? "    files: [\"lib.sld\"],\n    declaration: new Cons(intern(\"define-library\"), "))
  (test "a table that cannot restore has no restore" #t
        (has? "  \"test.other\": {\n    fingerprint: \"0ddba11\",\n    runtime: \"abcd1234\",\n    files: [\"other.sld\"],\n    procedures: {\n      \"g\": {\n        params: [],\n        rest: null,\n        constants: [],\n        make: (R, E, K) => {\n        body\n        }\n      }\n    }\n  }")))
